/**
 * BriefPanel.jsx
 * ───────────────
 * Renders the 2-paragraph Account Brief generated by tool_research_analyst.
 * Uses a card layout with colour-coded sections for pain points and alignment.
 */

import { BookOpen, AlertCircle, Target } from 'lucide-react'
import styles from './BriefPanel.module.css'

export default function BriefPanel({ brief }) {
  if (!brief) return null

  return (
    <section className={styles.panel} aria-label="Account brief">
      <h2 className={styles.title}>
        <BookOpen size={15} />
        Account Brief
      </h2>

      <div className={styles.grid}>
        {/* Pain Points */}
        <div className={`${styles.card} ${styles.pain}`}>
          <div className={styles.cardTitle}>
            <AlertCircle size={14} />
            Pain Points
          </div>
          <p className={styles.text}>{brief.pain_points}</p>
        </div>

        {/* Strategic Alignment */}
        <div className={`${styles.card} ${styles.align}`}>
          <div className={styles.cardTitle}>
            <Target size={14} />
            Strategic Alignment
          </div>
          <p className={styles.text}>{brief.strategic_alignment}</p>
        </div>
      </div>
    </section>
  )
}
